### ISSUE TITLE
ModuleNotFoundError Traceback

### ISSUE THREAD

**Issue by Dr-Barrote** [empa-scientific-it/python-tutorial#136] opened 2023-09-13 09:51 UTC
Hey folks, would really appreciate some support here. I have no idea what is happening, but somehow I get this error right at the intro when I'm trying to run the tests.

In the <%reload_ext tutorial.tests.testsuite>
I get

ModuleNotFoundError Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_14128\1023259248.py in
----> 1 get_ipython().run_line_magic('reload_ext', 'tutorial.tests.testsuite')

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
2362 kwargs['local_ns'] = self.get_local_scope(stack_depth)
2363 with self.builtin_trap:
-> 2364 result = fn(*args, **kwargs)
2365 return result
2366

C:\ProgramData\Anaconda3\lib\site-packages\decorator.py in fun(*args, **kw)
230 if not kwsyntax:
231 args, kw = fix(args, kw, sig)
--> 232 return caller(func, *(extras + args), **kw)
233 fun.name = func.name
234 fun.doc = func.doc

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\magic.py in (f, *a, **k)
185 # but it's overkill for just that one bit of state.
186 def magic_deco(arg):
--> 187 call = lambda f, *a, **k: f(*a, **k)
188
189 if callable(arg):

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\magics\extension.py in reload_ext(self, module_str)
61 if not module_str:
62 raise UsageError('Missing module name.')
---> 63 self.shell.extension_manager.reload_extension(module_str)

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\extensions.py in reload_extension(self, module_str)
128 self.loaded.add(module_str)
129 else:
--> 130 self.load_extension(module_str)
131
132 def _call_load_ipython_extension(self, mod):

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\extensions.py in load_extension(self, module_str)
78 if module_str not in sys.modules:
79 with prepended_to_syspath(self.ipython_extension_dir):
---> 80 mod = import_module(module_str)
81 if mod.file.startswith(self.ipython_extension_dir):
82 print(("Loading extensions from {dir} is deprecated. "

C:\ProgramData\Anaconda3\lib\importlib_init_.py in import_module(name, package)
125 break
126 level += 1
--> 127 return _bootstrap._gcd_import(name[level:], package, level)
128
129

C:\ProgramData\Anaconda3\lib\importlib_bootstrap.py in _gcd_import(name, package, level)

C:\ProgramData\Anaconda3\lib\importlib_bootstrap.py in find_and_load(name, import)

C:\ProgramData\Anaconda3\lib\importlib_bootstrap.py in find_and_load_unlocked(name, import)

C:\ProgramData\Anaconda3\lib\importlib_bootstrap.py in _load_unlocked(spec)

C:\ProgramData\Anaconda3\lib\importlib_bootstrap_external.py in exec_module(self, module)

C:\ProgramData\Anaconda3\lib\importlib_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

~\Documents\Training\empa_python\python-tutorial\tutorial\tests\testsuite.py in
6 from typing import Dict, Optional
7
----> 8 import ipynbname
9 import pytest
10 from IPython.core.display import Javascript

ModuleNotFoundError: No module named 'ipynbname'

**Comment by Dr-Barrote** [comment] 2023-09-13 10:05
I now ran it through miniconda3 with a conda 23.5-? and it worked!

**Comment by yakutovicha** [comment] 2023-09-13 10:35
From the traceback, it looks like you didn't activate the virtual environment that was supposed to be created at [this](https://github.com/empa-scientific-it/python-tutorial#2-create-a-dedicated-environment) step.

**Comment by Dr-Barrote** [comment] 2023-09-13 10:40
Yeah, I don't know, because it did create an environment, but I'm not sure it used binder. 
I did all the same steps but this time using miniconda and it worked. I'm still running locally and not using binder because I cannot access binder for some reason. I tried the launch|binder button on the main page of the [official repository on GitHub](https://github.com/empa-scientific-it/python-tutorial) of the tutorial.

**Comment by Dr-Barrote** [comment] 2023-09-13 10:43
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/srv/conda/lib/python3.11/site-packages/conda/exception_handler.py", line 16, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/srv/conda/lib/python3.11/site-packages/conda_env/cli/main.py", line 49, in do_call
        exit_code = getattr(module, func_name)(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/srv/conda/lib/python3.11/site-packages/conda/notices/core.py", line 123, in wrapper
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/srv/conda/lib/python3.11/site-packages/conda_env/cli/main_update.py", line 139, in execute
        result[installer_type] = installer.install(prefix, specs, args, env)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/srv/conda/lib/python3.11/site-packages/mamba/mamba_env.py", line 153, in mamba_install
        transaction.fetch_extract_packages()
    RuntimeError: Could not set URL (code: 14 - url = /setuptools-67.7.2-pyhd8ed1ab_0.conda)

`$ /srv/conda/bin/mamba update -p /srv/conda/envs/notebook --file binder/environment.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=/srv/conda/envs/notebook
                CONDA_DIR=/srv/conda
           CONDA_PLATFORM=linux-64
               CONDA_ROOT=/srv/conda
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/home/jovyan/.local/bin:/home/jovyan/.local/bin:/srv/conda/envs/notebo
                          ok/bin:/srv/conda/bin:/srv/npm/bin:/usr/local/sbin:/usr/local/bin:/usr
                          /sbin:/usr/bin:/sbin:/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /home/jovyan/.condarc
 populated config files : /srv/conda/.condarc
          conda version : 23.5.2
    conda-build version : not installed
         python version : 3.11.5.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.27=0
                          __linux=5.15.0=0
                          __unix=0=0
       base environment : /srv/conda  (writable)
      conda av data dir : /srv/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /srv/conda/pkgs
                          /home/jovyan/.conda/pkgs
       envs directories : /srv/conda/envs
                          /home/jovyan/.conda/envs
               platform : linux-64
             user-agent : conda/23.5.2 requests/2.31.0 CPython/3.11.5 Linux/5.15.0-79-generic ubuntu/18.04.6 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

time: 50.200

**Comment by yakutovicha** [comment] 2023-09-13 11:03
After conducting some online research, I couldn't locate a definitive explanation for the current situation. Since your local setup works, it's plausible that the problem is linked to connection issues, which may naturally resolve within the next day or two.

I propose to wait a little bit. If the issues remain unresolved, we have a closer look.

**Comment by edoardob90** [comment] 2023-10-03 09:54
The problem is still there when using Binder, same error. More specifically:

```
    Traceback (most recent call last):
      File "/srv/conda/lib/python3.11/site-packages/conda/exception_handler.py", line 16, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/srv/conda/lib/python3.11/site-packages/conda_env/cli/main.py", line 49, in do_call
        exit_code = getattr(module, func_name)(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/srv/conda/lib/python3.11/site-packages/conda/notices/core.py", line 123, in wrapper
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/srv/conda/lib/python3.11/site-packages/conda_env/cli/main_update.py", line 139, in execute
        result[installer_type] = installer.install(prefix, specs, args, env)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/srv/conda/lib/python3.11/site-packages/mamba/mamba_env.py", line 153, in mamba_install
        transaction.fetch_extract_packages()
    RuntimeError: Could not set URL (code: 14 - url = /setuptools-67.7.2-pyhd8ed1ab_0.conda)
```

It's something related to the setup of the virtual environment inside the container run by Binder. Since I don't know how to reproduce the problem, I'll close this issue for now.

@Dr-Barrote Check out the README: you also have the option to run with Docker.

**Comment by edoardob90** [comment] 2023-10-04 08:29
This seems to be a problem with an update to Mamba. See #139 for details.

**Comment by yakutovicha** [comment] 2023-10-04 20:08
it looks like the issue persists. At least the binder didn't manage to start after #139 has been merged.

**Comment by edoardob90** [comment] 2023-10-10 09:17
#139 only affects the Docker image built by GitHub Workflows. Binder still build its own image unless we configure the repository differently. And I think they are still using a version of `repo2docker` with the problem with Mamba. That's my guess.

**Closed** 2023-10-10 11:45 UTC

**Comment by yakutovicha** [comment] 2023-10-10 14:11
I confirm that binder now works 👍
